# Generated by Django 4.0.2 on 2022-03-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('units', '0002_remove_units_code_alter_units_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='units',
            options={'verbose_name_plural': 'Đơn vị tính'},
        ),
        migrations.AlterField(
            model_name='units',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='units',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo'),
        ),
        migrations.AlterField(
            model_name='units',
            name='description',
            field=models.TextField(default='Input!..', null=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='units',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Tên Đvt'),
        ),
        migrations.AlterField(
            model_name='units',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày sữa'),
        ),
    ]
