# Generated by Django 4.0.2 on 2022-03-01 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_name_alter_groupdevice_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name_plural': 'Thiết bị'},
        ),
        migrations.AlterModelOptions(
            name='groupdevice',
            options={'verbose_name_plural': 'Nhóm thiết bị'},
        ),
    ]
