# Generated by Django 4.0.2 on 2022-02-23 07:38

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('units', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSupplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('name', models.TextField(unique=True, verbose_name='name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='description')),
                ('image', models.ImageField(default='No_image.png', upload_to='groupdevice/%Y/%m', verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='code')),
                ('name', models.TextField(unique=True, verbose_name='name')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('description', ckeditor.fields.RichTextField(null=True, verbose_name='description')),
                ('image', models.ImageField(default='No_image.png', upload_to='device/%Y/%m', verbose_name='image')),
                ('group_supplies', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplies.groupsupplies')),
                ('units', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='units.units')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
