# Generated by Django 4.0.2 on 2022-02-23 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsupplies',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='name',
            field=models.TextField(verbose_name='name'),
        ),
    ]
