# Generated by Django 4.0.3 on 2022-03-08 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies', '0003_alter_groupsupplies_options_alter_supplies_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsupplies',
            name='image',
            field=models.ImageField(default='No_image.png', upload_to='groupsupplies/%Y/%m', verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='image',
            field=models.ImageField(default='No_image.png', upload_to='supplies/%Y/%m'),
        ),
    ]
